server:
  port: 9191

spring:
  h2:
    console:
      enabled: true
  application:
    name: Z-Payment-Service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost